name: CI

on:
  push:
    branches: [ unstable-dev ]
  pull_request:
    branches: [ unstable-dev ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      - name: Run tests
        run: |
          poetry run pytest
